version: "3.9"

services:
  valorant-app:
    image: solaimon/valo-project-1:latest
    restart: unless-stopped
    env_file:
      - .env.production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "9000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: valo_db
      POSTGRES_USER: valo_user
      POSTGRES_PASSWORD: valo_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U valo_user -d valo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
